# Generated by Django 2.2.4 on 2020-03-21 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentNumber', models.IntegerField()),
                ('DepartmentName', models.CharField(max_length=200)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IT_company.Branches')),
            ],
        ),
    ]
