# Generated by Django 2.2.4 on 2020-03-22 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpName', models.CharField(max_length=100)),
                ('EmpSurname', models.CharField(max_length=100)),
                ('EmpPatronymic', models.CharField(max_length=100)),
                ('EmpPost', models.CharField(max_length=200)),
                ('EmpPhone', models.CharField(max_length=20)),
                ('EmpEmail', models.CharField(max_length=50)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IT_company.Department')),
            ],
        ),
    ]
