# Generated by Django 2.2.4 on 2020-03-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpName',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpPatronymic',
            field=models.CharField(max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpSurname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
