# Generated by Django 2.2.4 on 2020-03-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0007_servicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('ServicePrice', models.FloatField(verbose_name='Цена услуги')),
                ('ServiceDescription', models.TextField(verbose_name='Описание услуги')),
                ('ServicePeriod', models.CharField(max_length=100, verbose_name='Период предоставления услуги')),
                ('ServiceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IT_company.ServiceType', verbose_name='Тип услуги')),
            ],
        ),
    ]
