# Generated by Django 2.2.4 on 2020-03-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0009_auto_20200324_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itservice',
            old_name='Equipment',
            new_name='Equipments',
        ),
    ]
