# Generated by Django 2.2.4 on 2020-03-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0010_auto_20200324_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockAddress', models.TextField(verbose_name='Адрес склада')),
                ('StockPhone', models.CharField(max_length=10, verbose_name='Телефон склада')),
            ],
        ),
    ]
