# Generated by Django 2.2.4 on 2020-03-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0012_equipment_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProviderName', models.CharField(max_length=200, verbose_name='Наименование поставщика')),
                ('ProviderPhone', models.CharField(max_length=10, verbose_name='Телефон поставщика')),
                ('ProviderEmail', models.CharField(max_length=50, verbose_name='E-mail поставщика')),
            ],
        ),
    ]
