# Generated by Django 2.2.4 on 2020-03-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0013_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='Provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_company.Provider'),
        ),
    ]
