# Generated by Django 2.2.4 on 2020-03-29 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0014_equipment_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='itservice',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='EquipmentName',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='EquipmentQuantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_company.Provider', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IT_company.Stock', verbose_name='Склад'),
        ),
    ]
