# Generated by Django 2.2.4 on 2020-03-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0015_auto_20200329_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itservice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='slug',
        ),
    ]
