# Generated by Django 2.2.4 on 2020-03-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0017_auto_20200330_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='itservice',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
