# Generated by Django 2.2.4 on 2020-03-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0018_itservice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='itservice',
            name='ServiceAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
