# Generated by Django 2.2.4 on 2020-03-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0019_itservice_serviceavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itservice',
            name='ServiceAvailable',
            field=models.BooleanField(default=True, verbose_name='Предоставляется?'),
        ),
    ]
