# Generated by Django 2.2.4 on 2020-03-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0020_auto_20200330_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
