# Generated by Django 2.2.4 on 2020-03-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0021_auto_20200330_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itservice',
            name='slug',
        ),
    ]
