# Generated by Django 2.2.4 on 2020-03-31 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0023_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ITService',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IT_company.ITService', verbose_name='Выбранные услуги'),
        ),
    ]
