# Generated by Django 2.2.4 on 2020-04-04 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0029_auto_20200402_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ITService',
        ),
        migrations.AddField(
            model_name='order',
            name='ITService',
            field=models.ManyToManyField(to='IT_company.ITService', verbose_name='Выбранные услуги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 15, 47, 1, 715536, tzinfo=utc), verbose_name='Дата заказа'),
        ),
    ]
