# Generated by Django 2.2.4 on 2020-04-05 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0031_auto_20200406_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IT_company.Post', verbose_name='Должность'),
        ),
    ]
