# Generated by Django 2.2.4 on 2020-04-08 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0033_auto_20200406_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='User',
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(default=datetime.date(2020, 4, 9), verbose_name='Дата заказа'),
        ),
    ]
