# Generated by Django 2.2.4 on 2020-04-13 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0036_auto_20200412_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(default=datetime.date(2020, 4, 13), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderStatus',
            field=models.CharField(blank=True, choices=[('Создан', 'Создан'), ('Обрабатывается', 'Обрабатывается'), ('Выполнен', 'Выполнен')], default='Создан', max_length=50, null=True, verbose_name='Статус заказа'),
        ),
    ]
