# Generated by Django 2.2.4 on 2020-04-25 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0038_auto_20200425_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderStatus',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Обрабатывается', 'Обрабатывается'), ('Выполнен', 'Выполнен')], default='Создан', max_length=50, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='PaymentMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IT_company.PaymentMethod', verbose_name='Способ оплаты'),
        ),
    ]
