# Generated by Django 2.2.4 on 2020-05-01 15:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0039_auto_20200425_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(default=datetime.date(2020, 5, 1), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderStatus',
            field=models.CharField(blank=True, choices=[('Создан', 'Создан'), ('Обрабатывается', 'Обрабатывается'), ('Выполнен', 'Выполнен')], default='Создан', max_length=50, null=True, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='ProviderPhone',
            field=models.CharField(max_length=20, verbose_name='Телефон поставщика'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='TypeDescription',
            field=models.TextField(verbose_name='Описание типа'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='TypeName',
            field=models.CharField(max_length=200, verbose_name='Название типа'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='StockPhone',
            field=models.CharField(max_length=20, verbose_name='Телефон склада'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractNumber', models.IntegerField(verbose_name='Номер договора')),
                ('ContractDate', models.DateField(verbose_name='Дата заключения договора')),
                ('ContractEndDate', models.DateField(verbose_name='Дата окончания договора')),
                ('ContractSum', models.FloatField(verbose_name='Сумма договора')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IT_company.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
    ]
