# Generated by Django 2.2.4 on 2020-05-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0044_auto_20200504_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(verbose_name='Дата заказа'),
        ),
    ]
