# Generated by Django 2.2.4 on 2020-05-04 16:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0045_auto_20200504_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 16, 41, 8, 126058, tzinfo=utc), verbose_name='Дата заказа'),
        ),
    ]
