# Generated by Django 2.2.4 on 2020-05-06 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0046_auto_20200504_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itservice',
            name='ServicePrice',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена услуги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 6, 19, 33, 59, 201683, tzinfo=utc), verbose_name='Дата заказа'),
        ),
    ]
