# Generated by Django 2.2.4 on 2020-05-06 19:42

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0047_auto_20200506_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itservice',
            name='ServicePrice',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цена услуги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 6, 19, 42, 27, 659152, tzinfo=utc), verbose_name='Дата заказа'),
        ),
    ]
