# Generated by Django 2.2.4 on 2020-05-06 19:44

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0048_auto_20200506_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 6, 19, 44, 59, 464928, tzinfo=utc), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма заказа'),
        ),
    ]
