# Generated by Django 2.2.4 on 2020-05-06 20:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0051_auto_20200506_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itservice',
            name='ServicePeriod',
            field=models.CharField(blank=True, choices=[('1 месяц', '1 месяц'), ('2 месяца', '2 месяца'), ('3 месяца', '3 месяца'), ('6 месяцев', '6 месяцев')], max_length=100, null=True, verbose_name='Период предоставления услуги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 6, 20, 22, 16, 285908, tzinfo=utc), verbose_name='Дата заказа'),
        ),
    ]
