# Generated by Django 2.2.4 on 2020-05-14 20:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IT_company', '0052_auto_20200506_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 14, 20, 50, 4, 585391, tzinfo=utc), verbose_name='Дата заказа'),
        ),
    ]
